# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: ltlf-decide
version: '0.0.0'
github: "ericthewry/ltlf-decide"
license: MIT
author: "Eric Campbell"
maintainer: "Eric Campbell"
# synopsis: A new Haskeleton package.
# description: ltlf-decide is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - QuickCheck
  - parsec
  - split
  - containers
  - graphviz
  - fgl
  - deepseq
  - timeit
  - argparser >=0.3.4
  - filepath
  source-dirs: library

executables:
  ltlf-decide:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - ltlf-decide
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  ltlf-decide-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - ltlf-decide
    - criterion
    - directory
    - filepath
    - split
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  ltlf-decide-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - ltlf-decide
    - tasty
    - tasty-hspec
    - hspec
    - QuickCheck
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
